id: I047BD644
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:13:48+00:00'
last_modified: '2022-06-07T15:05:14.429227+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21998
  title: མཛངས་བླུན་ཞེས་བྱ་བའི་མདོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6EB1:
      image_group_id: I1CZ2850
      title: ''
      total_pages: 490
      order: 1
      base_file: 6EB1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
