id: P001769
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:20:26.474392
source_metadata:
  id: bdr:W21998
  title: མཛངས་བླུན་ཞེས་བྱ་བའི་མདོ
  author: ''
  volumes:
    ca3e364280814966a83e92b763f57b5d:
      image_group_id: I1CZ2850
      title: ''
      volume_number: 1
      total_pages: 490
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
